<template><div class="page-view"><h1 class="page-title">{{ t('crawl.title') }}</h1><section class="form-card"><h2>{{ t('crawl.newTask') }}</h2><div class="m3-field"><label>{{ t('crawl.sourceType') }}</label><div class="m3-row"><label v-for="option in sourceTypes" :key="option.value" class="m3-choice"><md-radio name="source" :value="option.value" :checked="form.sourceType === option.value" @change="form.sourceType = option.value" />{{ option.label }}</label></div></div><div class="m3-field"><md-outlined-text-field :label="t('crawl.input')" :value="form.sourceId" :placeholder="inputPlaceholder" @input="form.sourceId = ($event.target as HTMLInputElement).value" @keydown.enter="handleSubmit" /></div><div class="m3-field"><label>{{ t('crawl.outputFormats') }}</label><div class="m3-row"><label v-for="format in ['txt','markdown']" :key="format" class="m3-choice"><md-checkbox :checked="form.formats.includes(format)" @change="toggleFormat(format, ($event.target as HTMLInputElement).checked)" />{{ format === 'txt' ? 'TXT' : 'Markdown' }}</label></div></div><md-filled-button :disabled="submitting" @click="handleSubmit">{{ t('crawl.start') }}</md-filled-button></section><div v-if="message" class="m3-alert" :class="messageType">{{ message }}</div></div></template>
<script setup lang="ts">
import { computed, onMounted, ref } from "vue"; import { useRoute, useRouter } from "vue-router"; import { useI18n } from "vue-i18n"; import { useTaskStore } from "../stores/tasks"; import { errorMessage } from "../api/tauri"; import { parsePixivUrl } from "../utils/pixivUrl";
const { t } = useI18n(); const route = useRoute(); const router = useRouter(); const taskStore = useTaskStore(); const form = ref({ sourceType: "single", sourceId: "", formats: ["txt", "markdown"] }); const submitting = ref(false); const message = ref(""); const messageType = ref("info");
const sourceTypes = computed(() => ["single", "series", "user"].map(value => ({ value, label: t(`crawl.${value}`) }))); const inputPlaceholder = computed(() => t(`crawl.inputPlaceholder.${form.value.sourceType}`));
function toggleFormat(format: string, checked: boolean) { form.value.formats = checked ? [...form.value.formats, format] : form.value.formats.filter(value => value !== format); } function extractId(input: string) { const parsed = parsePixivUrl(input); return parsed && ["novel-single", "novel-series", "user"].includes(parsed.kind) ? parsed.id : input.trim(); }
onMounted(() => { if (typeof route.query.sourceType === "string" && ["single", "series", "user"].includes(route.query.sourceType)) form.value.sourceType = route.query.sourceType; if (typeof route.query.sourceId === "string") form.value.sourceId = route.query.sourceId; if (route.query.sourceType || route.query.sourceId) router.replace({ query: {} }); });
async function handleSubmit() { const sourceId = extractId(form.value.sourceId); if (!sourceId) { message.value = t("crawl.invalidInput"); messageType.value = "error"; return; } submitting.value = true; message.value = ""; try { const result = await taskStore.createTask(form.value.sourceType, sourceId, form.value.formats); if (result.error) { message.value = result.error; messageType.value = "error"; } else { message.value = t("crawl.taskCreated", { id: result.task_id }); messageType.value = "success"; form.value.sourceId = ""; } } catch (error) { message.value = errorMessage(error) || t("crawl.createFailed"); messageType.value = "error"; } finally { submitting.value = false; } }
</script>
